apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-app
  labels:
    app: llmops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llmops
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: llmops
        app.kubernetes.io/version: "v1"
    spec:
      containers:
      - name: llmops-container
        image: llmops-app:1.0.0 # Use local image
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8501
            name: http
            protocol: TCP
        # Mount persistent store for chroma DB
        volumeMounts:
          - name: chroma-storage
            mountPath: /app/chroma_db
            readOnly: false

        # Resource requests & limits
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits: 
            cpu: "1"
            memory: "2Gi"

        # Startup/Readiness/Liveness probes
          # Adjust "path" if your app exposes a custom health endpoint.
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 3
        envFrom:
          - secretRef:
              name: llmops-secrets # Optional

        securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false   # if your app writes disk, keep false
      volumes:
        - name: chroma-storage
          persistentVolumeClaim:
            claimName: chroma-pvc

---
# --------------------------
# PersistentVolumeClaim for chroma DB (example, uses default storage class)
# --------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: llmops-service
  labels:
    app: llmops
spec:
  type: LoadBalancer
  selector:
    app: llmops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      name: http